#ifndef INPUT_PROCESSOR_C
#define INPUT_PROCESSOR_C

#include "util.h"

typedef struct UserType User;


#define OPENAI_DECOMPOSITION_SCHEMA_JSON \
"{" \
  "\"type\":\"object\"," \
  "\"additionalProperties\":false," \
  "\"required\":[\"profesie\",\"emotie\",\"pasiuni\",\"generalitati\",\"subiectiv\"]," \
  "\"properties\":{" \
    "\"profesie\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"emotie\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"pasiuni\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"generalitati\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"subiectiv\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}" \
  "}" \
"}"


void DecomposeInputIntoGraph(String *input, User *user);

#endif
